GHOST_DANCER_PROFILES = [
    {"dance_name": "Wes the MAB", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "UnkDes", "aliases": "", "source_note": "Mentioned as a form respondent / dancer card interest."},
    {"dance_name": "Greklite", "aliases": "", "source_note": "Mentioned as a form respondent / dancer card interest."},
    {"dance_name": "DC", "aliases": "", "source_note": "Mentioned as a form respondent / dancer card interest and battle record."},
    {"dance_name": "Haz Money", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "E Solo", "aliases": "", "source_note": "Mentioned as a form respondent and battle record."},
    {"dance_name": "SHOWDEM", "aliases": "Slim-Goodies", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Bre Dash", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Paul Gee", "aliases": "", "source_note": "Mentioned as a form respondent / music contributor."},
    {"dance_name": "Visionsz", "aliases": "", "source_note": "Mentioned as Flex dance name in form response."},
    {"dance_name": "BSNYEA", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "PRockz", "aliases": "P Rockz", "source_note": "Mentioned as a form respondent and battle record."},
    {"dance_name": "BOLITE", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Sah", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Future", "aliases": "", "source_note": "Mentioned as a form respondent and battle record."},
    {"dance_name": "Strike Litening", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Note", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "ICEMAN", "aliases": "", "source_note": "Mentioned as a form respondent / dancer card interest."},
    {"dance_name": "Koopa", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Ty Shotz", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Nhim Lite", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Hype Baby", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Smoove Biz", "aliases": "Chubz", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Na Na", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Seed", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "SammyC", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Kid Smoove", "aliases": "K Smoove", "source_note": "Mentioned as a form respondent, featured dancer suggestion, and battle record."},
    {"dance_name": "Fox Lite", "aliases": "", "source_note": "Mentioned as a form respondent and battle record."},
    {"dance_name": "Venom", "aliases": "", "source_note": "Mentioned as a form respondent and battle record."},
    {"dance_name": "Ray-Dot", "aliases": "", "source_note": "Mentioned as a form respondent."},
    {"dance_name": "Phresh Tune", "aliases": "", "source_note": "Mentioned as a form respondent / music contributor."},
    {"dance_name": "Ginger Spice", "aliases": "", "source_note": "Mentioned as a form respondent and battle record."},
    {"dance_name": "K Cosmic", "aliases": "", "source_note": "Mentioned as a form respondent and battle record."},

    {"dance_name": "Giz Da Wiz", "aliases": "Giz the Wiz, Gizmo", "source_note": "Mentioned in battle records."},
    {"dance_name": "Tweek Baby", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Dot Lite", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Tokyo", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Man From Da Video", "aliases": "Man From The Video", "source_note": "Mentioned in battle records."},
    {"dance_name": "Mr YouTube", "aliases": "Mr. YouTube", "source_note": "Mentioned in battle records and LiteFeet history responses."},
    {"dance_name": "Hype Star", "aliases": "Hypestar", "source_note": "Mentioned in battle records."},
    {"dance_name": "Teeth", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Ky Butta", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Jay Wavvy", "aliases": "Jay Wavy", "source_note": "Mentioned in battle records."},
    {"dance_name": "Noah Lot", "aliases": "", "source_note": "Mentioned in battle records and music responses."},
    {"dance_name": "J Black", "aliases": "Jay Black", "source_note": "Mentioned in battle records."},
    {"dance_name": "Larry Smoove", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "40 Pounds", "aliases": "40 Poundz", "source_note": "Mentioned in battle records."},
    {"dance_name": "K Smoove", "aliases": "Kid Smoove", "source_note": "Mentioned in battle records."},
    {"dance_name": "DuckSauce", "aliases": "Duck Sauce", "source_note": "Mentioned in battle records."},
    {"dance_name": "O Wizard", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Matt Live", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember and battle record."},
    {"dance_name": "Jada Chanel", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Money Mase", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Dope", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Sha Money X", "aliases": "", "source_note": "Mentioned as a connected dancer."},
    {"dance_name": "Slim Baby", "aliases": "", "source_note": "Mentioned as a connected dancer."},
    {"dance_name": "Vick Live", "aliases": "", "source_note": "Mentioned as a connected dancer."},
    {"dance_name": "D Lite", "aliases": "", "source_note": "Mentioned in battle records and dancer suggestions."},
    {"dance_name": "Kid The Wiz", "aliases": "KidTheWiz", "source_note": "Mentioned in battle records and history/music responses."},
    {"dance_name": "T Rex", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Buzz Lite", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Rell Smoove", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Supa Nova", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Robbie Rob", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Tah Swag", "aliases": "", "source_note": "Mentioned in music/battle responses."},
    {"dance_name": "Sparkz Rah", "aliases": "", "source_note": "Mentioned in music responses."},
    {"dance_name": "Uncle Gz", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "B Lyve", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "SNS", "aliases": "Sns", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Lady Live", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Tee The Creative", "aliases": "TEE THE CREATIVE", "source_note": "Mentioned as a dancer/community figure to feature/remember."},
    {"dance_name": "Ash Rocket", "aliases": "ASH ROCKET", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Xo Wavy", "aliases": "", "source_note": "Mentioned as a dancer to feature/remember."},
    {"dance_name": "Sky Boogz", "aliases": "", "source_note": "Mentioned in arena/battle responses."},
    {"dance_name": "Spank", "aliases": "", "source_note": "Mentioned in arena responses."},
    {"dance_name": "Spider Jackson", "aliases": "", "source_note": "Mentioned in dancer card battle/moment response."},
    {"dance_name": "Young Pop", "aliases": "", "source_note": "Mentioned in battle/moment responses."},
    {"dance_name": "X Live", "aliases": "", "source_note": "Mentioned in battle/moment responses."},
    {"dance_name": "Flii Boogie", "aliases": "Fli Boogie, Flii boogie", "source_note": "Mentioned in battle records."},
    {"dance_name": "Moe Black", "aliases": "", "source_note": "Mentioned in battle/moment responses."},
    {"dance_name": "Mr Jones", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Jo Smooth", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Trell Mix", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Mel Butta", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Nae Davis", "aliases": "Nay Davis", "source_note": "Mentioned in battle records."},
    {"dance_name": "Supreme", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Jay Bullet", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "K Shakes", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Tee Slims", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "So Q", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Top Star", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Tugz", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Zebb Live", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Kid Patt", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Chrybaby", "aliases": "Chrybaby Cozie, Daniel Holloway", "source_note": "Mentioned in battle records and LiteFeet history responses."},
    {"dance_name": "Sylencer", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Crazy C", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "40 Kal", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Mel Live", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Moon Live", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "2 Eazy", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Melly Mellz", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Richie Rich", "aliases": "", "source_note": "Mentioned in battle records."},
    {"dance_name": "Trebuckz", "aliases": "", "source_note": "Mentioned in battle/moment responses."},
    {"dance_name": "Rich Dollaz", "aliases": "", "source_note": "Mentioned in battle/moment responses."},
    {"dance_name": "Kid Mix", "aliases": "", "source_note": "Mentioned as a clash/counter dancer."},
    {"dance_name": "Top Villian", "aliases": "Top Villain", "source_note": "Mentioned as a clash/counter dancer."},
    {"dance_name": "Smoove Eazy", "aliases": "", "source_note": "Mentioned as a clash/counter dancer."},
    {"dance_name": "Top Fliqht", "aliases": "Top Flight", "source_note": "Mentioned as a clash/counter dancer."},
    {"dance_name": "Kid Fox", "aliases": "", "source_note": "Mentioned as a clash/counter dancer."},
    {"dance_name": "Splash Ocean", "aliases": "", "source_note": "Mentioned as a clash/counter dancer."}
]
